### PR TITLE
Allow restriction messages to be configured in admin 

### PR DESCRIPTION
**Pull request by cklosowski**
#17

### CODE REVIEW

**Comment by cklosowski** [comment]
@mindctrl @pippinsplugins are we good with this PR? I'd like to try and get this release out before weeks end.

**Comment by pippinsplugins** [comment]
I'm happy

**Comment by mindctrl** [comment]
@cklosowski I left a comment somewhere about needing wpautop. I don't see it right now.

**Comment by mindctrl** [comment]
@cklosowski https://github.com/easydigitaldownloads/EDD-Content-Restriction/issues/17#issuecomment-140913195

**Pull request merged**
